nama = input('siapa namanya bro?? ')
umur = input('umurmu berapa bro?? ')
cita = input('kamu mau jadi apa?? ')
hobi = input('kalau waktu luang seringnya ngapain?? ')
Question = input('Apakah Virgi ganteng (Y/N)? ')
Y = print('Sangat tampan')
N = print('Benar - Benar tampan')
print('haloo masbro..salam kenal, ' + nama + '.' + ' kamu berumur ' + umur + ' tahun.' + ' senang bertemu :)' + '.' + ' wahh..' + cita + ' masa depan nih,' +' kamu suka ' + hobi + ' kan?.'+ 'Oh iya, Aku Virgi. Btw, makasih ya udah nganggep aku ' + Question)